import { Tweak } from "./types";

export const s23UltraTweaks: Tweak[] = [
  {
    id: "vrr_96hz",
    title: "Otimização de Taxa Dinâmica (96Hz Max)",
    description: "Configura a taxa de atualização máxima para 96Hz para economizar até 15% de bateria, mantendo a fluidez visual quase idêntica a 120Hz.",
    category: "refresh_rate",
    command: "adb shell settings put secure peak_refresh_rate 96.0\nadb shell settings put secure min_refresh_rate 24.0",
    explanation: "O S23 Ultra suporta taxas variáveis (VRR). Forçar o teto para 96Hz reduz o estresse na GPU Snapdragon 8 Gen 2 e estende drasticamente o tempo de tela ativa (SOT).",
    impact: { performance: 4, battery: 5, safety: "Alto" },
    s23Specific: true,
  },
  {
    id: "vrr_force_120",
    title: "Fluidez Extrema (120Hz Constantes)",
    description: "Força o painel Dynamic AMOLED 2X a operar na taxa máxima de 120Hz em todos os aplicativos, evitando quedas de animações na interface.",
    category: "refresh_rate",
    command: "adb shell settings put secure min_refresh_rate 120.0\nadb shell settings put secure peak_refresh_rate 120.0",
    explanation: "Evita que o sistema reduza a frequência para 10Hz/24Hz ao ler textos, eliminando o efeito de 'micro-stutter' ao voltar a scrollar rapidamente.",
    impact: { performance: 5, battery: 2, safety: "Alto" },
    s23Specific: true,
  },
  {
    id: "disable_ram_plus",
    title: "Desativar RAM Plus (Fim dos Microgargalos)",
    description: "Desativa a memória virtual que usa o armazenamento UFS 4.0 do S23 Ultra como RAM. Melhora o tempo de resposta e reduz engasgos.",
    category: "performance",
    command: "adb shell settings put global ram_expand_size_list 0",
    explanation: "Embora o UFS 4.0 do S23 Ultra seja rápido, a memória virtual cria ciclos extras de paginação que podem gerar pequenas travadas. Desativar força o aparelho a usar puramente os 8GB/12GB de RAM física ultrarrápida LPDDR5X.",
    impact: { performance: 5, battery: 4, safety: "Alto" },
    s23Specific: true,
  },
  {
    id: "animation_snappy",
    title: "Interface Ultrarrápida (Animações 0.5x)",
    description: "Altera as escalas de animação e transição do Android pela metade, tornando as respostas visuais instantâneas.",
    category: "performance",
    command: "adb shell settings put global window_animation_scale 0.5\nadb shell settings put global transition_animation_scale 0.5\nadb shell settings put global animator_duration_scale 0.5",
    explanation: "Reduz o tempo gasto renderizando transições na One UI, dando a sensação de que o S23 Ultra está muito mais responsivo.",
    impact: { performance: 5, battery: 4, safety: "Alto" },
    s23Specific: false,
  },
  {
    id: "vulkan_rendering",
    title: "Ativar Engine Gráfica Vulkan (VUCAN)",
    description: "Força o renderizador do sistema HWUI (Hardware UI) a utilizar as APIs de baixo nível Vulkan em vez do OpenGL ES no Snapdragon 8 Gen 2.",
    category: "vulkan",
    command: "adb shell setprop debug.hwui.renderer vulkan\nadb shell setprop debug.renderengine.backend vulkan",
    explanation: "Acelera as operações de desenho da One UI, reduzindo gargalos na CPU e aproveitando ao máximo as instruções da GPU Adreno 740, fornecendo renderizações ultra fluidas.",
    impact: { performance: 5, battery: 4, safety: "Alto" },
    s23Specific: true,
  },
  {
    id: "camera_speed_hq",
    title: "Otimizar Latência da Câmera (Zero Shutter Lag)",
    description: "Otimiza a taxa de quadros e latência do viewfinder para capturas instantâneas sem travamentos ou delays no obturador do S23 Ultra.",
    category: "camera",
    command: "adb shell device_config put camera_native_viewfinder speed_priority 1\nadb shell settings put secure camera_double_tap_power_gesture_enabled 1",
    explanation: "Prioriza a velocidade de visualização e remove delays de pós-processamento secundários em fotos de ação instantânea.",
    impact: { performance: 4, battery: 3, safety: "Alto" },
    s23Specific: true,
  },
  {
    id: "bluetooth_ldac_force",
    title: "Priorizar Bluetooth HQ & LDAC (Estúdio)",
    description: "Força o bit-rate máximo de transmissão do codec LDAC (990kbps) e ignora restrições de volume de segurança no fone.",
    category: "audio",
    command: "adb shell settings put global bluetooth_ldac_playback_quality 1000\nadb shell settings put global bluetooth_a2dp_codec_priority 1\nadb shell settings put global audio_safe_volume_state 2",
    explanation: "Elimina oscilações de qualidade em fones premium (como Galaxy Buds ou Sony WH-1000XM5) e garante potência total de amplificação.",
    impact: { performance: 4, battery: 3, safety: "Alto" },
    s23Specific: false,
  },
  {
    id: "screen_anti_green_low_brightness",
    title: "Proteção de Tela: Anti-Flicker & Green Tint",
    description: "Ajusta as propriedades de taxa de atualização e limite físico de brilho para evitar o defeito de 'tela verde' em baixo brilho AMOLED.",
    category: "screen_protection",
    command: "adb shell settings put system screen_brightness_mode 0\nadb shell settings put system screen_brightness 50\nadb shell settings put secure min_refresh_rate 120.0",
    explanation: "Bloqueia o brilho físico do display em uma voltagem estável acima do ponto crítico de transição de cor AMOLED. Desativa o auto-brilho e força 120Hz constante para evitar oscilações de cinza/verde.",
    impact: { performance: 4, battery: 3, safety: "Alto" },
    s23Specific: true,
  },
  {
    id: "debloat_bixby",
    title: "Remover Bixby & Assistentes Invisíveis",
    description: "Desativa o assistente Bixby e serviços relacionados em segundo plano para liberar memória RAM e ciclos de processamento.",
    category: "debloat",
    command: "adb shell pm disable-user --user 0 com.samsung.android.bixby.agent\nadb shell pm disable-user --user 0 com.samsung.android.bixby.wakeup",
    explanation: "Executa a desativação de usuário nível 0 de forma segura. O aplicativo não rodará mais e não consumirá recursos, mas pode ser reativado se necessário.",
    impact: { performance: 4, battery: 4, safety: "Alto" },
    s23Specific: true,
  },
  {
    id: "debloat_ads_samsung",
    title: "Bloquear Telemetria e Anúncios de Sistema",
    description: "Desativa pacotes que realizam telemetria de anúncios e relatórios de mercado integrados pela Samsung.",
    category: "debloat",
    command: "adb shell pm disable-user --user 0 com.samsung.android.ipsgeofence\nadb shell pm disable-user --user 0 com.samsung.android.rubin.app",
    explanation: "O serviço Rubin monitora padrões de uso para anúncios personalizados. Desativar economiza dados e protege a privacidade.",
    impact: { performance: 3, battery: 4, safety: "Alto" },
    s23Specific: true,
  },
  {
    id: "axmanager_sideload_allow",
    title: "Permitir Sideload no AxManager",
    description: "Configura o Android para permitir de forma limpa o sideload de plugins modificados pelo AxManager sem avisos de integridade ou Play Protect.",
    category: "axmanager",
    command: "adb shell settings put global install_non_market_apps 1\nadb shell settings put secure package_verifier_enable 0",
    explanation: "Desativa a verificação invasiva de assinaturas de depuração para instalar APKs e plugins customizados sem avisos de segurança redundantes.",
    impact: { performance: 3, battery: 3, safety: "Médio" },
    s23Specific: false,
  },
  {
    id: "axmanager_cache_optim",
    title: "Otimizador de Cache de Áudio AxManager",
    description: "Aumenta os limites de buffer TCP para conexões de streaming de áudio Wi-Fi para reproduzir músicas Hi-Fi instantaneamente.",
    category: "axmanager",
    command: "adb shell settings put global wifi_bounce_delay 50\nadb shell settings put global tcp_buffersize_wifi \"4096,87380,1102080,4096,16384,1102080\"",
    explanation: "Melhora o throughput de transmissão de dados Wi-Fi, permitindo que plugins de streaming do AxManager façam cache sem buffer.",
    impact: { performance: 4, battery: 3, safety: "Alto" },
    s23Specific: false,
  },
  {
    id: "dolby_music_hq",
    title: "Forçar Dolby Atmos em Modo Música HQ",
    description: "Ativa e força o algoritmo Dolby Atmos no perfil ideal de música diretamente pelas configurações internas ocultas do sistema.",
    category: "audio",
    command: "adb shell settings put system dolby_effect_mode 1\nadb shell settings put system sound_alive_effect_profile 2",
    explanation: "Melhora a separação espacial e claridade sonora ao ouvir músicas com fones de ouvido bluetooth ou nos alto-falantes estéreo do S23 Ultra.",
    impact: { performance: 3, battery: 3, safety: "Alto" },
    s23Specific: true,
  },
  {
    id: "vulkan_threads",
    title: "Otimizar Threads e Filas Gráficas (Vulkan Async)",
    description: "Força o processamento assíncrono de sombreadores (shaders) e renderização paralela multithread para reduzir engasgos em jogos pesados e na One UI.",
    category: "vulkan",
    command: "adb shell setprop debug.renderengine.backend vulkan\nadb shell setprop debug.graphics.game_default_vulkan 1\nadb shell setprop debug.renderengine.vulkan.threads 4",
    explanation: "Divide a carga de trabalho de renderização gráfica entre múltiplos núcleos do Snapdragon 8 Gen 2, aproveitando melhor os clusters de CPU de alto desempenho para alimentar a Adreno 740.",
    impact: { performance: 5, battery: 3, safety: "Alto" },
    s23Specific: true,
  },
  {
    id: "adreno_boost",
    title: "Otimizar Driver Adreno e Latência de Frame",
    description: "Habilita as otimizações integradas do driver Adreno da Qualcomm para gerenciar recursos do framebuffer em taxas elevadas de atualização.",
    category: "vulkan",
    command: "adb shell setprop ro.hardware.egl adreno\nadb shell setprop ro.hardware.vulkan adreno\nadb shell setprop debug.gr.num_framebuffers 3\nadb shell setprop debug.egl.hw 1",
    explanation: "Força o uso explícito dos binários de aceleração por hardware e configura triple buffering para evitar engasgos em renderizações complexas na tela do S23 Ultra.",
    impact: { performance: 5, battery: 3, safety: "Alto" },
    s23Specific: true,
  },
  {
    id: "hw_overlay_disable",
    title: "Desabilitar Sobreposições de Tela (Composição de GPU)",
    description: "Força o sistema a usar sempre a GPU Adreno para composição de tela, aliviando o processador principal e eliminando atraso de frames.",
    category: "vulkan",
    command: "adb shell service call SurfaceFlinger 1008 i32 1",
    explanation: "Ao forçar a GPU a gerenciar a sobreposição de telas diretamente, o sistema economiza CPU e as transições tornam-se incrivelmente mais suaves, ideal para interações a 120 FPS.",
    impact: { performance: 5, battery: 3, safety: "Médio" },
    s23Specific: false,
  },
  {
    id: "game_driver_force",
    title: "Forçar Driver Gráfico de Sistema (Pronto para Jogos)",
    description: "Instrui o Android a usar o driver gráfico de sistema atualizado em vez do driver padrão para aplicativos de alta demanda visual.",
    category: "vulkan",
    command: "adb shell settings put global game_driver_all_apps 1",
    explanation: "Garante que todos os aplicativos instalados e emuladores utilizem os patches de otimização gráfica mais recentes do driver Adreno atualizado da Samsung.",
    impact: { performance: 4, battery: 3, safety: "Alto" },
    s23Specific: true,
  }
];
